jazzy \
--clean \
--author Ivlev \
--author_url https://github.com/ivlevAstef \
--github_url https://github.com/ivlevAstef/DITranquillity \
--github-file-prefix https://github.com/ivlevAstef/DITranquillity/tree/master \
--module-version 3.8.0 \
--xcodebuild-arguments -scheme,DITranquillity-iOS \
--module DITranquillity \
--root-url https://github.com/ivlevAstef/DITranquillity/code/ \
--output Documentation/code/
